import type { WeeklySummary } from '../storage/weekly-summary.js';

interface SlackHeaderBlock {
  readonly type: 'header';
  readonly text: { readonly type: 'plain_text'; readonly text: string };
}

interface SlackSectionBlock {
  readonly type: 'section';
  readonly fields: ReadonlyArray<{ readonly type: 'mrkdwn'; readonly text: string }>;
}

interface SlackDividerBlock {
  readonly type: 'divider';
}

interface SlackContextBlock {
  readonly type: 'context';
  readonly elements: ReadonlyArray<{ readonly type: 'mrkdwn'; readonly text: string }>;
}

type SlackBlock = SlackHeaderBlock | SlackSectionBlock | SlackDividerBlock | SlackContextBlock;

export type SlackBlockKitPayload = {
  readonly blocks: readonly SlackBlock[];
};

export function formatSlackDigest(summary: WeeklySummary): SlackBlockKitPayload {
  const totalCost = summary.totalCostUsd?.toFixed(4) ?? '—';
  const avgEfficiency =
    summary.avgEfficiencyScore != null ? (summary.avgEfficiencyScore * 100).toFixed(1) : '—';
  const topAntiPatternEntry = Object.entries(summary.antiPatternCounts ?? {}).sort(
    ([, a], [, b]) => b - a,
  )[0];
  const topAntiPattern = topAntiPatternEntry ? topAntiPatternEntry[0] : 'none';
  const safeTopAntiPattern = topAntiPattern.replace(/[\`\n]/g, '_');

  const blocks: SlackBlock[] = [
    {
      type: 'header',
      text: { type: 'plain_text', text: '🤖 Weekly AI Coding Summary' },
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Total Cost:*\n$${totalCost}` },
        { type: 'mrkdwn', text: `*Avg Efficiency:*\n${avgEfficiency}/100` },
        { type: 'mrkdwn', text: `*Sessions:*\n${summary.sessionCount}` },
        { type: 'mrkdwn', text: `*Top Anti-pattern:*\n\`${safeTopAntiPattern}\`` },
      ],
    },
  ];

  // Read defensively — summaries persisted to disk before this field existed
  // won't have it, same as this file's existing antiPatternCounts fallback.
  const platforms = Object.entries(summary.perPlatform ?? {});
  if (platforms.length > 1) {
    blocks.push({
      type: 'section',
      fields: platforms.map(([platform, stats]) => {
        const eff =
          stats.avgEfficiencyScore != null ? (stats.avgEfficiencyScore * 100).toFixed(1) : '—';
        return {
          type: 'mrkdwn' as const,
          text: `*${platform}:*\n${stats.sessionCount} sessions, ${eff}/100 efficiency`,
        };
      }),
    });

    const visibilityLevels = new Set(platforms.map(([, stats]) => stats.visibilityLevel));
    if (visibilityLevels.size > 1) {
      blocks.push({
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: '_These platforms have different instrumentation coverage — differences above may reflect what each platform lets Preflight observe, not actual developer behavior._',
          },
        ],
      });
    }
  }

  blocks.push(
    { type: 'divider' },
    {
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: '_Generated by Preflight_',
        },
      ],
    },
  );

  return { blocks };
}
