import type { WeeklySummary } from '../storage/weekly-summary.js';

interface SlackHeaderBlock {
  readonly type: 'header';
  readonly text: { readonly type: 'plain_text'; readonly text: string };
}

interface SlackSectionBlock {
  readonly type: 'section';
  readonly fields: ReadonlyArray<{ readonly type: 'mrkdwn'; readonly text: string }>;
}

interface SlackDividerBlock {
  readonly type: 'divider';
}

interface SlackContextBlock {
  readonly type: 'context';
  readonly elements: ReadonlyArray<{ readonly type: 'mrkdwn'; readonly text: string }>;
}

type SlackBlock = SlackHeaderBlock | SlackSectionBlock | SlackDividerBlock | SlackContextBlock;

export type SlackBlockKitPayload = {
  readonly blocks: readonly SlackBlock[];
};

export function formatSlackDigest(summary: WeeklySummary): SlackBlockKitPayload {
  const totalCost = summary.totalCostUsd?.toFixed(4) ?? '—';
  const avgEfficiency =
    summary.avgEfficiencyScore != null ? (summary.avgEfficiencyScore * 100).toFixed(1) : '—';
  const topAntiPatternEntry = Object.entries(summary.antiPatternCounts ?? {}).sort(
    ([, a], [, b]) => b - a,
  )[0];
  const topAntiPattern = topAntiPatternEntry ? topAntiPatternEntry[0] : 'none';
  const safeTopAntiPattern = topAntiPattern.replace(/[\`\n]/g, '_');

  return {
    blocks: [
      {
        type: 'header',
        text: { type: 'plain_text', text: '🤖 Weekly AI Coding Summary' },
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*Total Cost:*\n$${totalCost}` },
          { type: 'mrkdwn', text: `*Avg Efficiency:*\n${avgEfficiency}/100` },
          { type: 'mrkdwn', text: `*Sessions:*\n${summary.sessionCount}` },
          { type: 'mrkdwn', text: `*Top Anti-pattern:*\n\`${safeTopAntiPattern}\`` },
        ],
      },
      {
        type: 'divider',
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: '_Generated by Preflight_',
          },
        ],
      },
    ],
  };
}
