import type { SessionMetrics, BaselineMetrics } from './metrics-fetcher.js';

function formatCost(usd: number): string {
  return `$${usd.toFixed(4)}`;
}

function formatDelta(current: number, baseline: number): string {
  if (baseline === 0) return '—';
  const pct = ((current - baseline) / baseline) * 100;
  const sign = pct >= 0 ? '+' : '';
  return `${sign}${pct.toFixed(1)}%`;
}

function efficiencyEmoji(score: number | null): string {
  if (score === null) return '—';
  if (score >= 70) return '🟢';
  if (score >= 40) return '🟡';
  return '🔴';
}

export function formatReport(
  current: SessionMetrics,
  baseline: BaselineMetrics,
  sinceHours: number,
  developer: string,
): string {
  const effScore =
    current.efficiencyScore !== null
      ? `${efficiencyEmoji(current.efficiencyScore)} ${current.efficiencyScore.toFixed(1)}/100`
      : '—';

  const baselineEffStr =
    baseline.avgEfficiencyScore !== null ? baseline.avgEfficiencyScore.toFixed(1) : '—';

  const lines: string[] = [
    `## 🤖 AI Coding Assistant Report`,
    ``,
    `_Developer: \`${developer}\` · Window: last ${sinceHours}h · Baseline: 7-day average_`,
    ``,
    `| Metric | This Period | 7-day Baseline | Delta |`,
    `|--------|-------------|----------------|-------|`,
    `| Cost | ${formatCost(current.totalCostUsd)} | ${formatCost(baseline.avgDailyCostUsd)}/day | ${formatDelta(current.totalCostUsd, baseline.avgDailyCostUsd)} |`,
    `| Efficiency Score | ${effScore} | ${baselineEffStr} | — |`,
    `| Sessions | ${current.sessionCount} | — | — |`,
    ``,
  ];

  if (current.topAntiPatterns.length > 0) {
    lines.push(`### Anti-patterns detected`);
    lines.push(``);
    for (const p of current.topAntiPatterns) {
      lines.push(`- \`${p.type}\`: ${p.count}×`);
    }
    lines.push(``);
  }

  if (current.modelBreakdown.length > 0) {
    lines.push(`### Model usage`);
    lines.push(``);
    lines.push(`| Model | Cost |`);
    lines.push(`|-------|------|`);
    for (const m of current.modelBreakdown) {
      lines.push(`| \`${m.model}\` | ${formatCost(m.costUsd)} |`);
    }
    lines.push(``);
  }

  lines.push(
    `_Generated by [NR AI Observatory](https://github.com/cdehaan/nr-ai-observatory)_`,
  );

  return lines.join('\n');
}
